// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PortalCatolicoBrasil.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241031035213_M02-AddNewDatabase")]
    partial class M02AddNewDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalCatolicoBrasil.Models.DiaMissa", b =>
                {
                    b.Property<int>("DiaMissaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaMissaId"));

                    b.Property<string>("DiaSemana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.HasKey("DiaMissaId");

                    b.HasIndex("IgrejaId");

                    b.ToTable("DiaMissa");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.Evento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataEncerramento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HorarioEncerramento")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeParoquia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.HoraMissa", b =>
                {
                    b.Property<int>("HoraMissaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoraMissaId"));

                    b.Property<int>("DiaMissaId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Hora1")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Hora2")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Hora3")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Hora4")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Hora5")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Hora6")
                        .HasColumnType("time");

                    b.HasKey("HoraMissaId");

                    b.HasIndex("DiaMissaId");

                    b.ToTable("HoraMissa");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.Igreja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeIgreja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Igreja");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.SantoDia", b =>
                {
                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Data");

                    b.ToTable("santo_do_dia");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.DiaMissa", b =>
                {
                    b.HasOne("PortalCatolicoBrasil.Models.Igreja", "Igreja")
                        .WithMany("DiaMissa")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.HoraMissa", b =>
                {
                    b.HasOne("PortalCatolicoBrasil.Models.DiaMissa", "DiaMissa")
                        .WithMany("HoraMissa")
                        .HasForeignKey("DiaMissaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaMissa");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.DiaMissa", b =>
                {
                    b.Navigation("HoraMissa");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.Igreja", b =>
                {
                    b.Navigation("DiaMissa");
                });
#pragma warning restore 612, 618
        }
    }
}
