// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCatolicoBrasil.Models;

#nullable disable

namespace PortalCatolicoBrasil.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PortalCatolicoBrasil.Models.Antifona", b =>
                {
                    b.Property<int>("AntifonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AntifonaID"), 1L, 1);

                    b.Property<string>("Comunhao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ofertorio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AntifonaID");

                    b.ToTable("antifona");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.Evangelho", b =>
                {
                    b.Property<int>("EvangelhoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvangelhoID"), 1L, 1);

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvangelhoID");

                    b.ToTable("evangelho");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.Liturgia", b =>
                {
                    b.Property<int>("LiturgiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiturgiaID"), 1L, 1);

                    b.Property<int?>("AntifonasAntifonaID")
                        .HasColumnType("int");

                    b.Property<string>("Comunhao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EvangelhoID1")
                        .HasColumnType("int");

                    b.Property<string>("LiturgiaText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oferendas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrimeiraLeituraID1")
                        .HasColumnType("int");

                    b.Property<int?>("SalmoID1")
                        .HasColumnType("int");

                    b.Property<string>("SegundaLeitura")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LiturgiaID");

                    b.HasIndex("AntifonasAntifonaID");

                    b.HasIndex("EvangelhoID1");

                    b.HasIndex("PrimeiraLeituraID1");

                    b.HasIndex("SalmoID1");

                    b.ToTable("Liturgias");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.PrimeiraLeitura", b =>
                {
                    b.Property<int>("PrimeiraLeituraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrimeiraLeituraID"), 1L, 1);

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrimeiraLeituraID");

                    b.ToTable("primeira_leitura");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.Salmo", b =>
                {
                    b.Property<int>("SalmoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalmoID"), 1L, 1);

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Refrao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalmoID");

                    b.ToTable("salmo");
                });

            modelBuilder.Entity("PortalCatolicoBrasil.Models.Liturgia", b =>
                {
                    b.HasOne("PortalCatolicoBrasil.Models.Antifona", "Antifonas")
                        .WithMany()
                        .HasForeignKey("AntifonasAntifonaID");

                    b.HasOne("PortalCatolicoBrasil.Models.Evangelho", "Evangelho")
                        .WithMany()
                        .HasForeignKey("EvangelhoID1");

                    b.HasOne("PortalCatolicoBrasil.Models.PrimeiraLeitura", "PrimeiraLeitura")
                        .WithMany()
                        .HasForeignKey("PrimeiraLeituraID1");

                    b.HasOne("PortalCatolicoBrasil.Models.Salmo", "Salmo")
                        .WithMany()
                        .HasForeignKey("SalmoID1");

                    b.Navigation("Antifonas");

                    b.Navigation("Evangelho");

                    b.Navigation("PrimeiraLeitura");

                    b.Navigation("Salmo");
                });
#pragma warning restore 612, 618
        }
    }
}
